repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: insert-license
      name: Add license for all Python files
      exclude: ^\.github/.*$|^.*/.*_vendor/
      files: \.py$|\.pyi$
      args:
        - --comment-style
        - "|#|"
        - --license-filepath
        - templates/license/LICENSE.txt
        - --fuzzy-match-generates-todo
    - id: insert-license
      name: Add license for all Markdown files
      files: \.md$
      exclude: PROVIDER_CHANGES.*\.md$|^.*/.*_vendor/
      args:
        - --comment-style
        - "<!--|| -->"
        - --license-filepath
        - templates/license/LICENSE.txt
        - --fuzzy-match-generates-todo
    - id: insert-license
      name: Add license for all other files
      exclude: ^\.github/.*$|^.*/.*_vendor/
      args:
        - --comment-style
        - "|#|"
        - --license-filepath
        - templates/license/LICENSE.txt
        - --fuzzy-match-generates-todo
      files: >
        \.cfg$|\.conf$|\.ini$|\.ldif$|\.properties$|\.readthedocs$|\.service$|\.tf$|Dockerfile.*$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.11.1'
  hooks:
  - id: mypy
    args: [
    '--disable-error-code', 'import-untyped',
    ]
    additional_dependencies:
      - fastapi
      - pika
      - pytest
      - sqlmodel
      - tenacity
