services:
  postgres-base:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - timer-network